// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StakeholderApi.Data;

#nullable disable

namespace StakeholderApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("StakeholderApi.Models.Stakeholder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Stakeholders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Organisation = "Venture Capital Partners",
                            Role = "Investor",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.johnson@example.com",
                            FirstName = "Bob",
                            LastName = "Johnson",
                            Organisation = "TechCorp Ltd",
                            Role = "Advisor",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carol.johnson@example.com",
                            FirstName = "Carol",
                            LastName = "Johnson",
                            Organisation = "Innovation Hub",
                            Role = "Partner",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david.johnson@example.com",
                            FirstName = "David",
                            LastName = "Johnson",
                            Organisation = "Global Ventures",
                            Role = "Board Member",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eva.johnson@example.com",
                            FirstName = "Eva",
                            LastName = "Johnson",
                            Organisation = "Apex Advisory",
                            Role = "Mentor",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "frank.johnson@example.com",
                            FirstName = "Frank",
                            LastName = "Johnson",
                            Organisation = "Horizon Capital",
                            Role = "Investor",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "grace.johnson@example.com",
                            FirstName = "Grace",
                            LastName = "Johnson",
                            Organisation = "BluePeak Group",
                            Role = "Advisor",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "henry.johnson@example.com",
                            FirstName = "Henry",
                            LastName = "Johnson",
                            Organisation = "Meridian Partners",
                            Role = "Partner",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "isla.johnson@example.com",
                            FirstName = "Isla",
                            LastName = "Johnson",
                            Organisation = "Summit Advisors",
                            Role = "Board Member",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "james.johnson@example.com",
                            FirstName = "James",
                            LastName = "Johnson",
                            Organisation = "Crestwood Holdings",
                            Role = "Mentor",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.williams@example.com",
                            FirstName = "Alice",
                            LastName = "Williams",
                            Organisation = "Venture Capital Partners",
                            Role = "Investor",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.williams@example.com",
                            FirstName = "Bob",
                            LastName = "Williams",
                            Organisation = "TechCorp Ltd",
                            Role = "Advisor",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carol.williams@example.com",
                            FirstName = "Carol",
                            LastName = "Williams",
                            Organisation = "Innovation Hub",
                            Role = "Partner",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david.williams@example.com",
                            FirstName = "David",
                            LastName = "Williams",
                            Organisation = "Global Ventures",
                            Role = "Board Member",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eva.williams@example.com",
                            FirstName = "Eva",
                            LastName = "Williams",
                            Organisation = "Apex Advisory",
                            Role = "Mentor",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "frank.williams@example.com",
                            FirstName = "Frank",
                            LastName = "Williams",
                            Organisation = "Horizon Capital",
                            Role = "Investor",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "grace.williams@example.com",
                            FirstName = "Grace",
                            LastName = "Williams",
                            Organisation = "BluePeak Group",
                            Role = "Advisor",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "henry.williams@example.com",
                            FirstName = "Henry",
                            LastName = "Williams",
                            Organisation = "Meridian Partners",
                            Role = "Partner",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "isla.williams@example.com",
                            FirstName = "Isla",
                            LastName = "Williams",
                            Organisation = "Summit Advisors",
                            Role = "Board Member",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "james.williams@example.com",
                            FirstName = "James",
                            LastName = "Williams",
                            Organisation = "Crestwood Holdings",
                            Role = "Mentor",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.smith@example.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            Organisation = "Venture Capital Partners",
                            Role = "Investor",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.smith@example.com",
                            FirstName = "Bob",
                            LastName = "Smith",
                            Organisation = "TechCorp Ltd",
                            Role = "Advisor",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carol.smith@example.com",
                            FirstName = "Carol",
                            LastName = "Smith",
                            Organisation = "Innovation Hub",
                            Role = "Partner",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david.smith@example.com",
                            FirstName = "David",
                            LastName = "Smith",
                            Organisation = "Global Ventures",
                            Role = "Board Member",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eva.smith@example.com",
                            FirstName = "Eva",
                            LastName = "Smith",
                            Organisation = "Apex Advisory",
                            Role = "Mentor",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "frank.smith@example.com",
                            FirstName = "Frank",
                            LastName = "Smith",
                            Organisation = "Horizon Capital",
                            Role = "Investor",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "grace.smith@example.com",
                            FirstName = "Grace",
                            LastName = "Smith",
                            Organisation = "BluePeak Group",
                            Role = "Advisor",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "henry.smith@example.com",
                            FirstName = "Henry",
                            LastName = "Smith",
                            Organisation = "Meridian Partners",
                            Role = "Partner",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "isla.smith@example.com",
                            FirstName = "Isla",
                            LastName = "Smith",
                            Organisation = "Summit Advisors",
                            Role = "Board Member",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "james.smith@example.com",
                            FirstName = "James",
                            LastName = "Smith",
                            Organisation = "Crestwood Holdings",
                            Role = "Mentor",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.brown@example.com",
                            FirstName = "Alice",
                            LastName = "Brown",
                            Organisation = "Venture Capital Partners",
                            Role = "Investor",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.brown@example.com",
                            FirstName = "Bob",
                            LastName = "Brown",
                            Organisation = "TechCorp Ltd",
                            Role = "Advisor",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2024, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carol.brown@example.com",
                            FirstName = "Carol",
                            LastName = "Brown",
                            Organisation = "Innovation Hub",
                            Role = "Partner",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2024, 8, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david.brown@example.com",
                            FirstName = "David",
                            LastName = "Brown",
                            Organisation = "Global Ventures",
                            Role = "Board Member",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2024, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eva.brown@example.com",
                            FirstName = "Eva",
                            LastName = "Brown",
                            Organisation = "Apex Advisory",
                            Role = "Mentor",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "frank.brown@example.com",
                            FirstName = "Frank",
                            LastName = "Brown",
                            Organisation = "Horizon Capital",
                            Role = "Investor",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "grace.brown@example.com",
                            FirstName = "Grace",
                            LastName = "Brown",
                            Organisation = "BluePeak Group",
                            Role = "Advisor",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2024, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "henry.brown@example.com",
                            FirstName = "Henry",
                            LastName = "Brown",
                            Organisation = "Meridian Partners",
                            Role = "Partner",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2024, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "isla.brown@example.com",
                            FirstName = "Isla",
                            LastName = "Brown",
                            Organisation = "Summit Advisors",
                            Role = "Board Member",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "james.brown@example.com",
                            FirstName = "James",
                            LastName = "Brown",
                            Organisation = "Crestwood Holdings",
                            Role = "Mentor",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2024, 10, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.taylor@example.com",
                            FirstName = "Alice",
                            LastName = "Taylor",
                            Organisation = "Venture Capital Partners",
                            Role = "Investor",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2024, 10, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.taylor@example.com",
                            FirstName = "Bob",
                            LastName = "Taylor",
                            Organisation = "TechCorp Ltd",
                            Role = "Advisor",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2024, 10, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carol.taylor@example.com",
                            FirstName = "Carol",
                            LastName = "Taylor",
                            Organisation = "Innovation Hub",
                            Role = "Partner",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2024, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david.taylor@example.com",
                            FirstName = "David",
                            LastName = "Taylor",
                            Organisation = "Global Ventures",
                            Role = "Board Member",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eva.taylor@example.com",
                            FirstName = "Eva",
                            LastName = "Taylor",
                            Organisation = "Apex Advisory",
                            Role = "Mentor",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "frank.taylor@example.com",
                            FirstName = "Frank",
                            LastName = "Taylor",
                            Organisation = "Horizon Capital",
                            Role = "Investor",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "grace.taylor@example.com",
                            FirstName = "Grace",
                            LastName = "Taylor",
                            Organisation = "BluePeak Group",
                            Role = "Advisor",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "henry.taylor@example.com",
                            FirstName = "Henry",
                            LastName = "Taylor",
                            Organisation = "Meridian Partners",
                            Role = "Partner",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "isla.taylor@example.com",
                            FirstName = "Isla",
                            LastName = "Taylor",
                            Organisation = "Summit Advisors",
                            Role = "Board Member",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "james.taylor@example.com",
                            FirstName = "James",
                            LastName = "Taylor",
                            Organisation = "Crestwood Holdings",
                            Role = "Mentor",
                            Title = "Mr"
                        });
                });

            modelBuilder.Entity("StakeholderApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
